In [1]:
import numpy as np

In [2]:
a = np.array([5,6])
b = np.array([[1,2],[3,4]])

In [3]:
a

array([5, 6])

In [4]:
a[0]

5

In [5]:
b

array([[1, 2],
       [3, 4]])

In [6]:
b[0]

array([1, 2])

In [7]:
b[0][1]

2

In [8]:
b[0].ndim
b.ndim

2

In [9]:
b[0].size

2

In [10]:
b.size

4

In [11]:
print(np.log(a))

[1.60943791 1.79175947]


In [12]:
print(np.exp(a))

[148.4131591  403.42879349]


In [13]:
c = np.array([16,2])

In [14]:
c.dot(a)

92

In [15]:
np.dot(a,b)

array([23, 34])

In [16]:
c - b[1]

array([13, -2])

In [17]:
a + b[0]

array([6, 8])

In [18]:
b.reshape(4)

array([1, 2, 3, 4])

In [19]:
b

array([[1, 2],
       [3, 4]])

In [20]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
b.T

array([[1, 3],
       [2, 4]])

In [22]:
np.append(b,[5])

array([1, 2, 3, 4, 5])

In [23]:
b

array([[1, 2],
       [3, 4]])

In [24]:
b = np.append(b,[[5,6]],axis=0)
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [25]:
b.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [27]:
np.tile([1,2,3,4],4)

array([1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4])

In [28]:
np.tile([[1,2],[2,1]],(4,3))

array([[1, 2, 1, 2, 1, 2],
       [2, 1, 2, 1, 2, 1],
       [1, 2, 1, 2, 1, 2],
       [2, 1, 2, 1, 2, 1],
       [1, 2, 1, 2, 1, 2],
       [2, 1, 2, 1, 2, 1],
       [1, 2, 1, 2, 1, 2],
       [2, 1, 2, 1, 2, 1]])

In [29]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [30]:
x = np.ones((8,8))
x

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [31]:
x[1:5,2:6] = 0;
x

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 0., 0., 0., 0., 1., 1.],
       [1., 1., 0., 0., 0., 0., 1., 1.],
       [1., 1., 0., 0., 0., 0., 1., 1.],
       [1., 1., 0., 0., 0., 0., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [32]:
y=np.random.random((2,2))
y

array([[0.82816226, 0.35971572],
       [0.16928864, 0.28159075]])

In [33]:
y.min()

0.169288641846567

In [34]:
y.max()

0.8281622614316919

In [35]:
y.mean()

0.40968934320930583

In [36]:
np.nonzero([0,1,0,2,0,0,3,0])

(array([1, 3, 6], dtype=int64),)